### ISSUE TITLE
Instructions Needs More Detail

### ISSUE THREAD

**Issue by tug69666** [cis3296f22/bettR#12]
To get your program up and running, it would definitely be a struggle especially for someone that isn't well versed in using a computer. Make the instructions concise without generalizing any step but at the same time, don't make the instructions too long either.

**Comment by aagarwal17** [comment]
The instructions listed are only for someone who would like to take the long route of running our application. A user only needs to click the webpage link listed at the beginning of the instructions in the ReadMe.
